# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrabalhandoComRest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrabalhandoComRest

  target 'TrabalhandoComRestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrabalhandoComRestUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'BFKit'
  pod 'SVPullToRefresh'
end
