# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrabalhandoComRest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrabalhandoComRest

  
  pod 'BFKit'
  pod 'SVPullToRefresh'
  pod 'EasyRest'
  pod 'EasyRest/LoggerBeaver'
  pod 'SwiftMessages'
  pod 'RealmSwift', '~> 3.0'
  # pod 'Alamofire'
  
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        compatibility_pods = ['Genome']
        if compatibility_pods.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
